### PR TITLE
Hyperparams as numbers.Real

### PR DESCRIPTION
**Pull request by msperber**
Using ```hyperparam.Scalar``` etc. in my config file led to a failing type check because ```Scalar``` is not a ```float```.

To solve this, I made ```Scalar``` an instance of Python's abstract base class ```numbers.Real```, and updated the type annotations to use numbers.Real instead of float. Also includes some general improvements toward more consistent type annotations.

I think as a general goal we should try to use the abstract base class type variants whenever possible (e.g. also for ```numbers.Integral```, and possibly for a new string-type ABC) because that will enable making hyperparams and ```!Ref``` to be compatible with these types.

Update: I also slightly updated ```DefinedSequence``` to use its first list item as initial value.

### CODE REVIEW

**Comment by msperber** [comment]
Sorry for the premature commit, but this should be ready now. I ran into trouble because ```DefinedSequence``` is mutable and therefore not hashable, and some bugchecking-code in persistence.py assumed that all serializable objects are hashable, but now no longer makes this assumption.

**Comment by msperber** [comment]
The main file to review would be ```hyper_params.py```. If this is fine, everything else should be, too.

**Comment by philip30** [comment]
LGTM, but why one of the test is failing?

**Comment by msperber** [comment]
Seems it was a Travis issue, restarting the test fixed it. I'll merge, thanks for taking a look!

**Pull request merged**
