### PR TITLE
Improved import conventions Pt 1

### PR DESCRIPTION
**Pull request by msperber**
Better import conventions will be helpful for avoiding circular imports, which are already a problem and will become even more so when adding exhaustive type annotations (#438).

As suggested in #439, this PR starts by renaming modules to avoid name clashes with variable names. For example, ```batcher``` is a well-used variable name, which prevents one from doing ```from xnmt import batcher``` because the module name will be shadowed by the variable name. This is probably the less debatable part of #439 because it reduces verbosity in most places rather than adding to it. E.g. ```import xnmt.batcher; xnmt.batcher.mark_as_batch()``` can now be replaced by ```from xnmt import batching; batching.mark_as_batch()```.

When renaming modules, I tried to be somehow consistent, but the main goal was to avoid name clashes with common variable names while keeping module names short. Let me know if you find anything confusing or have better naming suggestions.

### CODE REVIEW

**Comment by philip30** [comment]
Hmmm, it's hard to guess the correct module name in the future. There is abbreviated module (actually a file, python module is a whole folder), but there is also truncated name, or full name... I think the cleaner solution is using the full module path, but just rename them at the start of function/files, and we can guarantee to avoid clash. When the code get more bigger, it's hard to find not colliding name without using an escape like "_" for local variable. It's just my opinion.

**Comment by msperber** [comment]
Hmm it's true that we can't avoid all name clashes, but I think we should at least try as it is currently happening very frequently. But I can see your point that the names should make it easy to find classes in the code base... I made another attempt by using the main classes name as module name but then making it plural where appropriate, e.g. ```attenders``` and ```batchers```. This would be a smaller change to the names than before and should be easy to understand and avoid most name clashes..

**Comment by msperber** [comment]
Sure, I'll finalize this very soon. ```long_short_term_memory.py``` seems unnecessarily long, so I'd just call it ```recurrent.py```.

**Comment by neubig** [comment]
What about `recurrent_transducers` or something? I think it's OK to call it just `recurrent` as well (that's certainly less verbose), but as @philip30 pointed out, having some things plural some things not will make remembering the module names difficult.

**Comment by msperber** [comment]
Ok, done.

**Comment by neubig** [comment]
Thanks, merge if you're ready.

**Pull request merged**
