### PR TITLE
Return newly called constructor instead of deepcopy

### PR DESCRIPTION
**Pull request by neubig**
Fixes https://github.com/neulab/xnmt/issues/498

### CODE REVIEW

**Comment by msperber** [comment]
LGTM, and should probably be merged soon as this is a major bug.. failing tests seem to be related to @philip30's code expecting the ```segment``` attribute?

**Comment by neubig** [comment]
Yes, I've noticed this and was working on fixing it, but I have a bunch of meetings today so I don't have a whole lot of time. If someone else has time to do it I'm happy to pass it off.

**Comment by msperber** [comment]
Sure I'll take a look, this was caused by my sentence refactoring anyways.

**Comment by neubig** [comment]
Thanks! Looks like it's working now. I'll merge.

**Pull request merged**
