### PR TITLE
[WIP] Added ability to combine together dev scores

### PR DESCRIPTION
**Pull request by neubig**
This PR introduces the ability to combine together multiple development scores to determine the final score that should be used to do learning rate decay, etc. It also improves the documentation about the default of using the first development task.

The reason why this is "[WIP]" is because using `eval()` is a security hole: https://stackoverflow.com/questions/661084/security-of-pythons-eval-on-untrusted-strings

It'd be nice to be able to come up with a safe version.

Fixes https://github.com/neulab/xnmt/issues/293

### CODE REVIEW

**Comment by msperber** [comment]
For the record, YAML deserialization is actually also not safe because it allows creating arbitrary Python objects. However, it does have a load_safe method which is more restrictive and could be tried if we needed to.

Instead of eval, I guess we could try a serializable WeightedSum class that has configurable weights (including negative)? It would be much less flexible though, obviously.

And one more remark, I've also used ```eval()``` here, although it could probably be replaced by ```yaml.load()```: https://github.com/neulab/xnmt/blob/master/xnmt/xnmt_evaluate.py#L69

**Comment by msperber** [comment]
YAML also has a ```!!python/object:``` syntax for creating arbitrary objects, so I think you could do something like ```!!python/object:subprocess.Popen{ ... }``` to trick it into executing arbitrary commands. The ```yaml_tag``` is mostly to make things less verbose. I can take a look sometime, ideally the ```load_safe``` method would allow only the ```!``` syntax but not the ```!!python/object:``` one..

**Comment by pierregodard** [comment]
After being recently moved to `requirements-extra.txt`, `sentencepiece>=0.0.6` made it back to `requirements.txt` after this merge.

**Comment by msperber** [comment]
Update: I tried using ```yaml.safe_load```, but it seems it doesn't support the ```!``` syntax, so it would probably be considerable effort to prevent the creation of arbitrary objects via the XNMT config files.

**Pull request merged**
