### PR TITLE
Some Fixes

### PR DESCRIPTION
**Pull request by philip30**
Few fixes for:
- Preproc not working in python3
- matplotlib not working on a machine that does not run X-Server

### CODE REVIEW

**Comment by neubig** [comment]
Does preproc work on Python 2 after this PR?

**Comment by philip30** [comment]
Well, I guess so. I will write the test code later if wished.

**Comment by neubig** [comment]
Yeah, let's write a test and try to run it on Python2. The testing code now
works, so it should be easy to write a new unit test.

Graham

**Comment by philip30** [comment]
@neubig I added the test and also split the test into several files.

**Pull request merged**
