### PR TITLE
Remove deprecated reference to _dynet

### PR DESCRIPTION
**Pull request by armatthews**

### CODE REVIEW

**Comment by msperber** [comment]
LGTM, but could you rebase to avoid re-doing the previously committed changes and keep the git history clean?

**Comment by philip30** [comment]
This can be done by ```git merge master``` I guess. Be sure to pull the latest master branch.

**Comment by armatthews** [comment]
I don't see any changes between when I cloned and when I committed this. Nevertheless I just did a fetch upstream and merge. Did that fix things, or what else do I need to do?

**Comment by msperber** [comment]
Yes this did fix things (as indicated by github showing 5 lines changes now, instead of the 20+ from before the fix), thanks!

**Pull request merged**
