### PR TITLE
fixed and improved examples

### PR DESCRIPTION
**Pull request by msperber**
- fix and reorganize the examples. The idea is to have examples/ serve as kind of a tutorial, and later add a recipes/ directory with configs for tested, state-of-the-art models.
  - config files now begin with 01_, 02_, .. to help people know where to start
  - standard is split into a new standard example with more options specified (addressing #279), and a minimal example.
  - added some more introductory comments to some config files
  - fixed preproc example
  - moved some failing example to the test configs, marked with @unittest.expectedFailure
- dropout default is changed from 0.0 to 0.3, similar to OpenNMT

### CODE REVIEW

**Comment by philip30** [comment]
Actually I can't run the test file when there is a line checking there is a setting or not. Do you know the problem? It said that setting is not a recognized argument.

**Comment by msperber** [comment]
Hm could you tell me the exact command you used?

**Comment by philip30** [comment]
I tried both 

```
python3 test/test_run.py
python3 test/test_run.py --settings=settings.unittest
```

Both giving me the same error:
```
usage: test_run.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b]
                   [tests [tests ...]]
test_run.py: error: unrecognized arguments: --settings=settings.unittes
```

**Comment by msperber** [comment]
Ok I see. It works for me like this:
```
python -m unittest test.test_run
```
Thanks for catching it, and I also updated the docs accordingly.

**Comment by philip30** [comment]
Not really sure that I like the way we execute the 'module' rather than a script. Executing a module is a lot trickier I think. Can we preserve the functionality of the executable scripts with the settings?

**Comment by msperber** [comment]
I looked into it and it seems the issue is not script vs module, but that unittests should generally be run via 'python -m unittest', as indicated in the Python documentation: https://docs.python.org/3/library/unittest.html#command-line-interface

But you can also use ``python -m unittest test/test_run.py`` instead.

**Comment by neubig** [comment]
Thanks! This is nice.

**Pull request merged**
