### PR TITLE
Random search

### PR DESCRIPTION
**Pull request by msperber**
Feature that performs random search over model / search parameters, by simply specifying the choices in the config file. Search can be sequential or in parallel, depending on how experiment runner is started.

### CODE REVIEW

**Comment by neubig** [comment]
Nice idea. One simple question though, what if we want the encoder and decoder to have the same number of layers, but random? Is there any way to accommodate this?

**Comment by msperber** [comment]
That should be possible by doing random search over default_layer_dim (maybe manually fixing the other related parameters if the search should be only over encoder / decoder dim).

Otherwise, one could also try named random parameters and then somehow refer to that (it's possible that YAML supports something like that), but I'm not sure if that would make things too complicated?

**Comment by neubig** [comment]
Another option would be to make it possible for parameters to be references to other parameters (e.g. decoder_dim = encoder_dim), but this also seems a little bit complicated. One option is to just leave things as-is for now, and then fix this when it becomes a problem. If you agree, go ahead and merge :)

**Comment by msperber** [comment]
It was actually relatively easy, so now you can do something like:
    encoder:
      hidden_dim: !RandomParam
        values: [32,64]
    attention_context_dim: !RefParam
      ref: encoder.hidden_dim

**Comment by neubig** [comment]
Great, go ahead and merge this.

**Pull request merged**
