### PR TITLE
component sharing

### PR DESCRIPTION
**Pull request by msperber**
This drafts some code to make it possible to share YAML components. The idea is to use YAML anchors / aliases like this:
`    model: !DefaultTranslator`
`      src_embedder: !SimpleWordEmbedder &src_emb`
`      encoder: ...`
`      attender: ...`
`      trg_embedder: *src_emb`
`      decoder: ...`
In the deserialization code, we need to catch if something is an alias, assume that the corresponding anchor has already been initialized (so proper ordering does matter), and then simple reference to that object instead of initializing a new one.

Problem is that pyyaml completely resolves anchors and aliases and doesn't return any info on this. Possibly something like this could help (don't have time to look into it right now): https://github.com/ChloeTigre/pyyaml-keep-anchors

Otherwise, we could make our own referencing mechanism, but according to my first attempt in that direction, that might introduce complications to the param sharing code..

### CODE REVIEW

**Comment by msperber** [comment]
Actually I had a very simple idea for how this should work without installing additional packages etc, which I quickly wrote up.
It's untested but I expect the deserialization part of the sharing feature should basically work.

**Comment by msperber** [comment]
This should be ready to merge: Component sharing works, and I included an example for (1) sharing reference to the same object in memory, (2) copying over component config, but creating separate objects, and (3) referencing individual values.

One caveat: the sharing of embedders from the example is actually not working properly, because the vocabs are not shared. To make this work properly, we would either have to move the readers inside the model, or separate vocab and readers and move at least the vocabs inside the model (I think that would be an intuitive thing to do anyways).

**Comment by neubig** [comment]
Thanks, this looks really nice. One small comment: perhaps you could add a little bit of documentation to the beginning of the example yaml file? The types of sharing that you can do and syntax for realizing each of these was pretty difficult for me to grok based on what we currently have.

**Comment by msperber** [comment]
Sure, how about this?

**Comment by neubig** [comment]
Awesome, thanks! When you resolve the conflicts I think this is ready to merge.

**Pull request merged**
