### PR TITLE
Added support for an external evaluation script

### PR DESCRIPTION
**Pull request by roeeaharoni**
This pull request adds support for an external evaluation script, as supported in other NMT frameworks like Nematus and Marian. 

To use this feature, add: `external|path=PATH` to the `eval_metrics` configuration. The evaluation script in PATH should only print the evaluation score (and only it) before termination. 

In case a lower score is better, one should indicate it by setting `higher_better` to False, i.e.: `external|path=PATH|higher_better=False`

### CODE REVIEW

**Comment by neubig** [comment]
Thanks! But this re-opens the pipe every time a sentence is evaluated, right? This seems slow. Perhaps this could be reconciled with this issue? The interface specified there would allow the pipe to be open once upon initialization of the evaluator, then used over and over again: https://github.com/neulab/xnmt/issues/220

**Comment by roeeaharoni** [comment]
As far as I understood the current implementation, the evaluator's evaluate() is called once for the entire test set and not per sentence, so only one pipe will be opened in each evaluation. Note that the external script does not directly receive the outputs: it can either use the ones already written to a file by train.py before evaluation or decode them by itself.

**Comment by neubig** [comment]
@roeeaharoni Yeah, I guess that's right for the moment. We'll probably have to refactor a bit to do what I suggested, so I'll merge this PR first then we can go back and fix things later. Thanks!

**Comment by msperber** [comment]
This is currently breaking tests under Python 3.6, could you fix this @roeeaharoni ? It's probably just a matter of adding brackets to the print statements.

**Comment by roeeaharoni** [comment]
@msperber Added the missing print brackets in my fork (roeeaharoni/xnmt, xnmt_evaluate.py, line 66). I don't see the new commit in the pull request (probably since it is already merged) - should I create another pull request with the fix?

**Comment by msperber** [comment]
Sure, thanks!

**Comment by roeeaharoni** [comment]
@msperber done, see: https://github.com/neulab/xnmt/pull/252

**Pull request merged**
