### PR TITLE
Fix batcher

### PR DESCRIPTION
**Pull request by philip30**
Fix bugs in batcher.

### CODE REVIEW

**Comment by philip30** [comment]
#232

**Comment by philip30** [comment]
@neubig I don't understand why the test is failing. Can you help me to take a look?

**Comment by msperber** [comment]
Hey Philip, it's possible this is an import error. Could you check if the attender is imported somewhere before the YAML parser is called? I had a similar issue before and don't understand it completely, but adding an import helped in my case.

**Comment by philip30** [comment]
@msperber It runs OK in my environment, but it is just failing in travis-ci/pr. Did you have the same issue before? Thank you for the suggestion.

**Comment by msperber** [comment]
Hmm no, I had the same error message, but I did have it in my local environment as well.

**Comment by philip30** [comment]
I am merging it right now because it should run OK in most of the environments. This pr is only a bug fix also.

**Pull request merged**
