### PR TITLE
TF_New  (updated pull requests from https://github.com/neulab/xnmt/pull/246)

### PR DESCRIPTION
**Pull request by DevSinghSachan**
Created a new branch to resolve merge conflicts.

### CODE REVIEW

**Comment by philip30** [comment]
Hey @DevSinghSachan, I just want to give you a suggestion:
1. Could you create a more informative commit name? "New codes" does not explain anything.
2. Could you create several meaningful working commits and pushed at once? So your push will not spam my mailbox (since I am following github and many other people do). There is no point in pushing too many times I guess.

**Comment by philip30** [comment]
My another suggestion is to squash the commit into your current working branch and push forcedly. You can merge all those 11 commits into 1 commit with a name "Refactoring".

**Comment by DevSinghSachan** [comment]
Philip, sorry for spamming your mailboxes.
This is happening as I am not able to test the code in my local machine (due to dynet installation failure) and so I have to push small small commits every time, to debug where the code fails in the remote.

**Comment by philip30** [comment]
I see. What is the error? Maybe we can work it out.
If that is the case, I would suggest you to fork the code and do a pull request from your forked repository. You can always pull from this remote directory and keep working on your own xnmt repository. You won't spam people by doing that. This is actually the normal case in doing development when you don't have the access to write on the repository.

**Comment by philip30** [comment]
This is the update from #246

**Comment by DevSinghSachan** [comment]
Yes, this is the update of #246 . 
The code in earlier branch was working fine till today morning, but then due to other pull requests being merged in main xnmt, I was getting a several merge conflicts in the updated code. So, I decided to create  a new branch, although I am not sure if this is the correct way.

**Comment by DevSinghSachan** [comment]
Thanks Philip, I have opened an issue in dynet regarding the installation.
Forking the code is a great suggestion. From next feature addition onwards, yes, I will fork the code and then submit pull requests through it.

**Comment by philip30** [comment]
I think to create a new pull request to solve the conflict is not the correct way. You should resolve the merge conflict actually. If you create a new branch and copy-paste the code it can produce some unexpected errors. Thank you!

**Comment by DevSinghSachan** [comment]
Hey Philip, thanks again. 
I have rebased all my commits and merged them into a single commit.

**Comment by msperber** [comment]
Looks like there is some problem with Travis, but I can confirm that the tests pass on my machine under Python 3.6.

**Comment by neubig** [comment]
Thanks! I'll go and do some more tests, and also potentially create a later PR to try to merge TransformerTranslator into the standard translator (as much as possible at least).

**Pull request merged**
