### PR TITLE
fixing preprocessing tokenization

### PR DESCRIPTION
**Pull request by neubig**
OK, I started fixing https://github.com/neulab/xnmt/issues/234

Basically, I've figured out the problems:
- [x] In `preproc.yaml`, we need to add the `join-char` preprocessing step in `xnmt_decode`
- [x] We need to specify sentencepieced input and output in the yaml file
- [x] We need to fix the join-char step to treat unicode underscores as the thing to merge together (which is the sentencepiece default). This is done by default now, but for some reason is not working properly.

The following are things that we're probably not going to handle in this PR.

* Ideally, we'd like to be able to specify this separator in the config file, probably by passing in the output strategy as a class using the `!ClassName` syntax
* There is a problem with evaluation of likelihood and BLEU at dev time. Tokenized output files are necessary for evaluation of likelihood, but untokenized output files are necessary for evaluation of BLEU. Right now we can't specify both, so basically we need to use untokenized files and just ignore the poor likelihood scores.

### CODE REVIEW

**Comment by neubig** [comment]
Note: this also started to address #244 as well.

**Comment by john-hewitt** [comment]
I'd be happy to contribute post-Dec 15. I'll plan on it unless you're planning to get it done before then.

**Comment by neubig** [comment]
Added `join-piece` via https://github.com/neulab/xnmt/pull/255
And we probably don't need to specify the separator for this PR.

**Comment by neubig** [comment]
Most recent updates fixed https://github.com/neulab/xnmt/issues/249

**Comment by john-hewitt** [comment]
I've been testing this on a new Python 3.6 install and the encoding choice code in preproc.py is still giving errors for me. Will update later tonight.

**Comment by john-hewitt** [comment]
The directory to write the sentencepiece model to wasn't being created before sentencepiece tried to write the model. Error messages were then being suppressed by an unrelated condition. Fixed in #262.

**Pull request merged**
