### PR TITLE
word dropout

### PR DESCRIPTION
**Pull request by msperber**
- [X] implement word (type) dropout as in https://arxiv.org/abs/1512.05287
- [X] slightly unrelated bugfix: disable embedding weight noise at inference time
- [X] quick convergence test
- [X] simplified usage of recursive methods

### CODE REVIEW

**Comment by msperber** [comment]
@philip30 I'm a bit confused for how I can make ```set_train()``` work in the embedders. Maybe you could help me out? I called ```register_hier_child()``` [here](https://github.com/neulab/xnmt/pull/171/files#diff-fd01cb9452fd023aa34552ca193efb5cR74). The problem I have:
- If I have ```SimpleWordEmbedder``` inherit from ```model.HierarchicalModel```, I get this error: 'SimpleWordEmbedder' object has no attribute '_hier_children'
- I I don't, I get a warning and set_train() is never called: ('Skipping hierarchical construction:', 'SimpleWordEmbedder', 'is not a subclass of HierarchicalModel')

**Comment by philip30** [comment]
Hi @msperber, I think it is because you didn't call the super constructor in the SimpleWordEmbedder. The attribute is constructed there. I think this is not a good behaviour and confusing... Maybe you can change it a bit so it will be an attribute even though we are not calling the constructor of the HierarchicalModel?

**Comment by msperber** [comment]
Thanks, I got it! I refactored things a bit so we don't have to call the super constructor, hope it's okay. From my side this would be ready for merging then.

**Comment by neubig** [comment]
LGTM if @philip30 is OK.

**Comment by philip30** [comment]
LGTM

**Pull request merged**
